### ISSUE TITLE
Implement lookup_value_regex for nested resources

### ISSUE THREAD

**Issue by H0neyBadger** [alanjds/drf-nested-routers#39] opened 2015-01-07 17:47 UTC
With DRF 3, ViewSet’s **lookup_value_regex** property isn’t properly passed to the **SimpleRouter** overridden class.

I think you can remove the SimpleRouter from **/rest_framework_nested/routers.py** and use the default DRF **SimpleRouter.get_lookup_regex**

tested on :
 - Django 1.7
 - DRF 3
 - Python 3

**Comment by clintonb** [comment] 2015-07-13 23:19
I have confirmed that simply using the DRF's default `SimpleRouter` resolves this issue.

**Comment by qubird** [comment] 2015-07-17 13:12
This works to me, using DefaultRouter and NestedSimpleRouter. 

Sure this will be save time to many people:

I'm using UUIDs, so my regex was: `[0-9a-f]{32}`.

This was making the router falling over url formatting, because `{32}` is a meta-expression for python string formatting. I replaced `{32}` with `{{32}}` and it now works.

**Comment by stevejalim** [comment] 2015-07-17 13:15
I think that `{{32}}` find deserves a prize

**Comment by alanjds** [comment] 2015-08-24 03:15
Hi. Can you issue a PR for DRF 3 compatibility?, or at least explain an example on the README?

**Comment by mrhwick** [comment] 2015-11-17 19:15
This should all be fixed by #60 and #58

**Comment by alanjds** [comment] 2015-11-21 13:08
@mrhwick #60 and #58 was both merged. Can I close this one?

**Comment by mrhwick** [comment] 2015-11-30 15:47
@H0neyBadger was the original poster of the issue, but I would be surprised if any of the issues mentioned here are still outstanding with the latest fixes.

**Comment by alanjds** [comment] 2015-11-30 16:23
Closing. @H0neyBadger: Feel free to reopen if there is still an issue.

**Closed by alanjds** 2015-11-30 16:23 UTC
Labels: docs, enhancement, question
